import type { Listing } from "./types";

// Demo listings shown when no Supabase project is configured.
// Replace by setting NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.
export const DEMO_LISTINGS: Listing[] = [
  {
    id: "demo-1",
    slug: "community-hall-near-the-main-market-demo-1",
    title: "Community hall near the main market",
    category: "community_venue",
    zone: "Kawale 1",
    landmark: "Main market, next to the water point",
    description:
      "Large hall suitable for community meetings, ceremonies and trainings. Seats up to 120 people on benches. Chairs and tables can be arranged with advance notice. Daytime bookings preferred.",
    rooms: 1,
    capacity: 120,
    facilities: ["water", "toilet", "solar", "accessible"],
    priceMwk: 25000,
    depositMwk: null,
    billingPeriod: "daily",
    availableFrom: null,
    verified: true,
    verifiedAt: "2026-06-20",
    featured: true,
    providerName: "Umoja Community Centre",
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-01",
  },
  {
    id: "demo-2",
    slug: "training-room-with-electricity-and-internet-demo-2",
    title: "Training room with electricity and internet",
    category: "training_space",
    zone: "Lisungwi",
    landmark: "Near the youth centre",
    description:
      "Quiet training room for up to 25 participants. Reliable electricity, Wi-Fi, whiteboard and projector screen. Popular with NGOs running digital-skills courses — book early for weekday mornings.",
    rooms: 1,
    capacity: 25,
    facilities: ["electricity", "internet", "toilet", "furnished"],
    priceMwk: 15000,
    depositMwk: null,
    billingPeriod: "daily",
    availableFrom: null,
    verified: true,
    verifiedAt: "2026-06-28",
    featured: true,
    providerName: "Takenolab Training Centre",
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-05",
  },
  {
    id: "demo-3",
    slug: "small-office-room-furnished-demo-3",
    title: "Small office room, furnished",
    category: "office",
    zone: "Likuni 1",
    landmark: "Along the road to the health centre",
    description:
      "Furnished office room suitable for a small organisation or freelancer. Desk, two chairs and a lockable cabinet included. Shared toilet and water point in the compound.",
    rooms: 1,
    capacity: 4,
    facilities: ["furnished", "secure_lock", "water", "toilet", "solar"],
    priceMwk: 40000,
    depositMwk: 40000,
    billingPeriod: "monthly",
    availableFrom: "2026-08-01",
    verified: true,
    verifiedAt: "2026-07-01",
    featured: false,
    providerName: null,
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-10",
  },
  {
    id: "demo-4",
    slug: "market-side-shop-space-demo-4",
    title: "Market-side shop space",
    category: "shop",
    zone: "Kawale 2",
    landmark: "Main market, front row",
    description:
      "Shop space in a busy part of the market. Strong foot traffic on market days. Metal door with secure lock. Electricity connection available at extra cost.",
    rooms: 1,
    capacity: null,
    facilities: ["secure_lock"],
    priceMwk: 35000,
    depositMwk: 70000,
    billingPeriod: "monthly",
    availableFrom: null,
    verified: false,
    verifiedAt: null,
    featured: false,
    providerName: null,
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-25",
  },
  {
    id: "demo-5",
    slug: "carpentry-workshop-with-storage-demo-5",
    title: "Carpentry workshop with storage",
    category: "workshop",
    zone: "Katudza",
    landmark: "Behind the secondary school",
    description:
      "Covered workshop space previously used for carpentry. Includes an attached storage room. Solar power installed; suitable for light tools. Shared compound with one other business.",
    rooms: 2,
    capacity: null,
    facilities: ["solar", "secure_lock", "water"],
    priceMwk: 50000,
    depositMwk: 50000,
    billingPeriod: "monthly",
    availableFrom: "2026-07-15",
    verified: true,
    verifiedAt: "2026-06-15",
    featured: false,
    providerName: null,
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-05-30",
  },
  {
    id: "demo-6",
    slug: "dry-storage-room-lockable-demo-6",
    title: "Dry storage room, lockable",
    category: "storage",
    zone: "New Katubza",
    landmark: "Near the food distribution point",
    description:
      "Dry, secure storage room suitable for stock or equipment. Raised floor, iron sheets in good condition, strong door with two locks. Access by arrangement with the provider.",
    rooms: 1,
    capacity: null,
    facilities: ["secure_lock"],
    priceMwk: 20000,
    depositMwk: 20000,
    billingPeriod: "monthly",
    availableFrom: null,
    verified: true,
    verifiedAt: "2026-06-22",
    featured: false,
    providerName: null,
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-12",
  },
  {
    id: "demo-7",
    slug: "homestay-room-for-visitors-approved-operator-demo-7",
    title: "Homestay room for visitors (approved operator)",
    category: "homestay",
    zone: "Dzaleka Hill",
    landmark: "Five minutes from the cultural centre",
    description:
      "Private room in a family compound for visitors, operated through the approved homestay programme. Includes breakfast, mosquito net and solar lighting. Connected with Visit Dzaleka experiences.",
    rooms: 1,
    capacity: 2,
    facilities: ["furnished", "solar", "water", "toilet", "cooking"],
    priceMwk: 18000,
    depositMwk: null,
    billingPeriod: "daily",
    availableFrom: null,
    verified: true,
    verifiedAt: "2026-07-02",
    featured: true,
    providerName: "Visit Dzaleka Homestays",
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-06-18",
  },
  {
    id: "demo-8",
    slug: "meeting-room-for-small-groups-demo-8",
    title: "Meeting room for small groups",
    category: "meeting_venue",
    zone: "Zomba",
    landmark: "Church compound near the football ground",
    description:
      "Meeting room for up to 15 people, available on weekdays. Benches and a table provided. Quiet surroundings, suitable for committee meetings and study groups.",
    rooms: 1,
    capacity: 15,
    facilities: ["toilet", "accessible"],
    priceMwk: 8000,
    depositMwk: null,
    billingPeriod: "daily",
    availableFrom: null,
    verified: false,
    verifiedAt: null,
    featured: false,
    providerName: null,
    whatsapp: null,
    coverImagePath: null,
    coverImageBucket: null,
    coverImageUrl: null,
    createdAt: "2026-07-01",
  },
];
