import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ClipboardCheck,
  FileText,
  Flag,
  FolderOpen,
  Heart,
  HelpCircle,
  Home,
  LayoutDashboard,
  Map,
  MapPin,
  MessageSquare,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  UserRound,
  Users,
  Wrench,
} from "lucide-react";
import type { NavIconName } from "@/lib/nav-config";

export const NAV_ICONS: Record<NavIconName, LucideIcon> = {
  "badge-check": BadgeCheck,
  bell: Bell,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  clipboard: ClipboardCheck,
  "file-text": FileText,
  flag: Flag,
  folder: FolderOpen,
  heart: Heart,
  help: HelpCircle,
  home: Home,
  layout: LayoutDashboard,
  map: Map,
  "map-pin": MapPin,
  message: MessageSquare,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  user: UserRound,
  users: Users,
  wrench: Wrench,
};
